# Dockerfile.kafka_consumer

FROM python:3.9-slim

WORKDIR /app

# Copy requirements (already in deploy/)
COPY requirements_kafka.txt .

RUN pip install --no-cache-dir -r requirements_kafka.txt

# Copy source code from parent directory of deploy/
COPY ../src ./src

CMD ["python", "src/ingestion/real_time/kafka_consumer.py"]
