global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'batch_ingestor'
    static_configs:
      - targets: ['batch_ingestor:8000']